spring.application.name=banksys

# postgres settings
spring.datasource.url=jdbc:postgresql://localhost:5432/banksys
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa & hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# mcp server settings
spring.ai.mcp.server.name=banksys-mcp-server
spring.ai.mcp.server.protocol=streamable
server.port=8080

# ollama settings
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:3b

### mcp client settings
spring.ai.mcp.client.streamable-http.connections.banksys-mcp-server.url=http://localhost:8080
spring.ai.mcp.client.streamable-http.connections.banksys-mcp-server.endpoint=/mcp
spring.ai.mcp.client.initialized=false

# spring.main.web-application-type=none
# spring.main.banner-mode=off
# logging.pattern.console=